apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobs-${{ values.serviceName }}-${{ values.action }}
  namespace: default
  labels:
    app: cronjobs-${{ values.serviceName }}-${{ values.action }}
spec:
  schedule: "${{ values.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: cronjobs-${{ values.serviceName }}-${{ values.action }}
        spec:
          restartPolicy: Never
          tolerations:
            - key: "workload"
              operator: "Equal"
              value: "spot"
              effect: "NoSchedule"
          nodeSelector:
            karpenter.sh/capacity-type: spot
          containers:
            - name: cronjobs-${{ values.serviceName }}-${{ values.action }}
              image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/${{ values.ecrImageName }}:latest
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
