# Main Queue - consumer listens here
# When message is rejected/nacked, it goes to DLX -> DLQ -> back here after TTL
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: ${{ values.vhost }}-${{ values.queueName }}
  namespace: default
spec:
  name: ${{ values.queueName }}
  vhost: ${{ values.vhost }}
  type: quorum
  durable: true
  arguments:
    x-dead-letter-exchange: ${{ values.queueName }}.DLX
    x-dead-letter-routing-key: ${{ values.queueName }}
  rabbitmqClusterReference:
    name: rabbitmq-cluster
