apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.serviceName }}
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: ${{ values.acmCertArn }}
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/group.name: dsgpay
    alb.ingress.kubernetes.io/tags: Environment=production,Application=dsgpay
spec:
  ingressClassName: alb
  rules:
    - host: ${{ values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.serviceName }}
                port:
                  number: ${{ values.port }}
