apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{ values.fullName }}
  name: ${{ values.fullName }}
  namespace: default
spec:
  selector:
    matchLabels:
      app: ${{ values.fullName }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${{ values.fullName }}
    spec:
      containers:
        - name: ${{ values.fullName }}
          image: 589962364545.dkr.ecr.ap-southeast-1.amazonaws.com/${{ values.ecrImageName }}:latest
          env:
            - name: RABBIT_MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-user-bny3mk109inc-creds
                  key: username
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-user-bny3mk109inc-creds
                  key: password
            - name: RABBIT_MQ_URI
              value: "amqp://$(RABBIT_MQ_USERNAME):$(RABBIT_MQ_PASSWORD)@rabbitmq26.default.svc.cluster.local:5672/${{ values.vhost }}"
            - name: RABBIT_MQ_QUEUE
              value: "${{ values.queueName }}"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 300Mi
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      nodeSelector:
        karpenter.sh/capacity-type: spot
